### ISSUE TITLE
% is not working correctly on the Emulator.

### ISSUE THREAD

**Issue by HunseopJeong** [Samsung/TAU#964]
The following style do not work properly in the emulator.
``` css
{
   opacity: 100%;
}
```
Need to check how to fix the issue.
